//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InactiveAssistantMonitor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int PeriodIntervalActivityCheckInSeconds {
            get {
                return ((int)(this["PeriodIntervalActivityCheckInSeconds"]));
            }
            set {
                this["PeriodIntervalActivityCheckInSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int NumberOfIntervalsSessionActivityCheckUntilKill {
            get {
                return ((int)(this["NumberOfIntervalsSessionActivityCheckUntilKill"]));
            }
            set {
                this["NumberOfIntervalsSessionActivityCheckUntilKill"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\UiPath\\Studio\\")]
        public string UiPathAssistantPathX86 {
            get {
                return ((string)(this["UiPathAssistantPathX86"]));
            }
            set {
                this["UiPathAssistantPathX86"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UiPathAssistant\\UiPath.Assistant.exe")]
        public string UiPathAssistantExe {
            get {
                return ((string)(this["UiPathAssistantExe"]));
            }
            set {
                this["UiPathAssistantExe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UiRobot.exe")]
        public string UiPathRobot {
            get {
                return ((string)(this["UiPathRobot"]));
            }
            set {
                this["UiPathRobot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\UiPath\\Studio\\")]
        public string UiPathAssistantPath {
            get {
                return ((string)(this["UiPathAssistantPath"]));
            }
            set {
                this["UiPathAssistantPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://laptop-fq7ihb0c/")]
        public string OrchestratorUrl {
            get {
                return ((string)(this["OrchestratorUrl"]));
            }
            set {
                this["OrchestratorUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8080e263-2994-450d-aed4-498b7a78067d")]
        public string MachineKey {
            get {
                return ((string)(this["MachineKey"]));
            }
            set {
                this["MachineKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("130")]
        public int NumberOfIntervalsWithoutInputUntilKill {
            get {
                return ((int)(this["NumberOfIntervalsWithoutInputUntilKill"]));
            }
            set {
                this["NumberOfIntervalsWithoutInputUntilKill"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("45")]
        public int PeriodIntervalDelayedCheckOrchestrator {
            get {
                return ((int)(this["PeriodIntervalDelayedCheckOrchestrator"]));
            }
            set {
                this["PeriodIntervalDelayedCheckOrchestrator"] = value;
            }
        }
    }
}
